apiVersion: v1
kind: Service
metadata:
  name: sandbox-proxy
  labels:
    app: sandbox-proxy
spec:
  type: ClusterIP
  selector:
    app: sandbox-proxy
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
